name: flutter_contacts_service
description: "A new Flutter plugin To handle and manage contacts on Android and iOS natively."
version: 0.0.2
homepage: https://github.com/mustafa-707/flutter_contacts_service
repository: https://github.com/mustafa-707/flutter_contacts_service
issue_tracker: https://github.com/mustafa-707/flutter_contacts_service/issues

environment:
  sdk: ^3.0.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.0
  quiver: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_contacts_service
        pluginClass: FlutterContactsServicePlugin
      ios:
        pluginClass: FlutterContactsServicePlugin
